export const Images = {
  watchWidgetIcon: require("../assets/images/watchWidget.jpg"),
  laptopWidgetIcon: require("../assets/images/laptopWidget.jpg"),
  phoneWidgetIcon: require("../assets/images/phoneWidgt.jpg"),
  monitorWidgetIcon: require("../assets/images/monitorWidget.jpg"),
  fruitVegetableWidgetIcon: require("../assets/images/fruitVegetable.jpg"),
  stapleWidgetIcon: require("../assets/images/staple.jpg"),
  topDealsFreshWidgetIcon: require("../assets/images/topDealsFresh.jpg"),
  dairyWidgetIcon: require("../assets/images/dairy.jpg"),
  kitchen1Icon: require("../assets/images/kitchen1.jpg"),
  kitchen2Icon: require("../assets/images/kitchen2.jpg"),
  kitchen3Icon: require("../assets/images/kitchen3.jpg"),
  kitchen4Icon: require("../assets/images/kitchen4.jpg"),
  gardenIcon: require("../assets/images/garden.jpg"),
  fashion1Icon: require("../assets/images/fashion1.jpg"),
  fashion2Icon: require("../assets/images/fashion2.jpg"),
  fashion3Icon: require("../assets/images/fashion3.jpg"),
  fashion4Icon: require("../assets/images/fashion4.jpg"),
  homeDecor1Icon: require("../assets/images/homeDecor1.jpg"),
  homeDecor2Icon: require("../assets/images/homeDecor2.jpg"),
  homeDecor3Icon: require("../assets/images/homeDecor3.jpg"),
  homeDecor4Icon: require("../assets/images/homeDecor4.jpg"),
  cartIcon: require("../assets/images/trolley.png"),
  logo: require("../assets/images/logo.png"),
  noResults: require("../assets/images/no-results.png"),
  congrats: require("../assets/images/congrats.png"),
};
